[package]
name = "solana-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
serde = { version = "1.0.219", features = ["derive"] }
solana-client = "1.17.0"
solana-sdk = "2.2.1"
tokio = { version = "1.45.1", features = ["full"] }
